[package]
name = "Win32"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.56", features = [
    "Win32",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
] }
ssh2 = "0.9"
